---
# tasks file for httpd

- name: install GIT package
  yum: name=git state=present

- name: Installing httpd package
  yum: name=httpd state=present

- name: Starting and enabling the httpd service
  service: name=httpd state=started enabled=yes

- name: Deploy sample file from GIT
  git: repo=https://github.com/Bhadra09/samplehtml.git dest=/var/www/html


# name: copy configuration template
#  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf 

